Justin/style comments
ClearContracts/cardano-constitution-voting-app pull request #193
Opened 2024-11-27 22:45 UTC by justinschreiner

addresses more intersect style comments

2024-11-27 23:25 UTC, mattlaux requested changes
I assume this is from a change in this PR. Tough to see who I am logged in as.
<img width="477" alt="Screenshot 2024-11-27 at 5 24 05 PM" src="https://github.com/user-attachments/assets/3e8b847d-7bca-4a6e-8128-ed4adef0e10b">

2024-11-30 01:06 UTC, justinschreiner commented
change to green checkmark in representatives

2024-12-01 16:38 UTC, mattlaux approved these changes

2024-12-01 16:38 UTC, mattlaux commented on src/pages/index.tsx
> +  const theme = useTheme();
```suggestion
```

2024-12-01 16:38 UTC, mattlaux commented on src/pages/index.tsx
> +import { Box, Typography, useTheme } from '@mui/material';
```suggestion
import { Box, Typography } from '@mui/material';
```

2024-12-01 20:04 UTC, merged